# Generated by Django 4.0.5 on 2022-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.CharField(default='milanthapa299@gmail.com', max_length=200),
        ),
    ]
