# Generated by Django 4.0.5 on 2022-06-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_public',
            new_name='is_published',
        ),
    ]
